# Generated by Django 6.0.2 on 2026-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('web', 'Web Templates'), ('mobile', 'Mobile Apps'), ('plugin', 'Plugins & Extensions'), ('graphics', 'Graphics & Icons'), ('course', 'Courses & Tutorials')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
